--DDL KOMUTLARI

--CREATE DATABASE - DB OLUÞTURUR
CREATE DATABASE SatisVT


-- USE ÝLGÝLÝ DBYÝ KULLANARAK QUERYLERÝ ÇALIÞTIRIR.
USE SatisVT

--CREATE TABLE - TABLO OLUÞTURUR
Create table TBLKATEGORI
(
KATEGORIID int identity(1,1) PRIMARY KEY,
KATEGORIAD varchar(50) 
)

CREATE TABLE TBLURUNLER
(
URUNID int identity(1,1) PRIMARY KEY,
URUNAD VARCHAR(50),
MARKA VARCHAR(50),
URUNKATEGORI INT,
URUNALISFIYAT DECIMAL(18,2),
URUNSATISFIYAT DECIMAL(18,2),
URUNSTOK SMALLINT CHECK(URUNSTOK>0),
URUNDURUM BIT DEFAULT '1'
)

CREATE TABLE TBLPERSONEL
(
PERSONELID INT IDENTITY(1,1) PRIMARY KEY,
PERSONELAD VARCHAR(50)
)

CREATE TABLE TBLMUSTERI
(
MUSTERIID INT PRIMARY KEY IDENTITY(1,1),
MUSTERIAD VARCHAR(50),
MUSTERISOYAD VARCHAR(50),
MUSTERISEHIR VARCHAR(13),
MUSTERIBAKIYE DECIMAL(18,2)
)

CREATE TABLE TBLHAREKET
(
HAREKETID INT IDENTITY(1,1) PRIMARY KEY,
URUN INT,
MUSTERI INT,
PERSONEL INT,
ADET INT,
TUTAR DECIMAL(18,2),
TARIH SMALLDATETIME
)


TRUNCATE TABLE TBLURUNLER




--DML KOMUTLARI

INSERT INTO TBLKATEGORI (KATEGORIAD) VALUES ('BÝLGÝSAYAR')
INSERT INTO TBLKATEGORI (KATEGORIAD) VALUES ('BEYAZ EÞYA')
INSERT INTO TBLKATEGORI (KATEGORIAD) VALUES ('KÜÇÜK EV ALETLERÝ')
INSERT INTO TBLKATEGORI (KATEGORIAD) VALUES ('TV')


INSERT INTO TBLURUNLER (URUNAD,MARKA,URUNKATEGORI,URUNALISFIYAT,URUNSATISFIYAT,URUNSTOK) 
VALUES ('BUZDOLABI','BEKO',2,4300,5000,20)

UPDATE TBLURUNLER SET URUNAD='SU ISITICI' WHERE URUNAD='KETTLE'

SELECT KATEGORIAD,COUNT(*) AS [TOPLAM ÜRÜN SAYISI] FROM TBLURUNLER
INNER JOIN TBLKATEGORI
ON TBLURUNLER.URUNKATEGORI = TBLKATEGORI.KATEGORIID
GROUP BY KATEGORIAD
ORDER BY COUNT(*)

UPDATE TBLURUNLER SET URUNSATISFIYAT+=500 
WHERE URUNKATEGORI=(SELECT KATEGORIID FROM TBLKATEGORI WHERE KATEGORIAD='BÝLGÝSAYAR')

--TV KATEGORÝSÝNDEKÝ ÜRÜNLERÝN SATIÞFÝYATINA %10 ÝNDÝRÝM YAPAN SORGUYU YAZIN
UPDATE TBLURUNLER SET URUNSATISFIYAT=URUNSATISFIYAT*0.9 
WHERE URUNKATEGORI = (SELECT KATEGORIID FROM TBLKATEGORI WHERE KATEGORIAD='TV')


SELECT URUNID, URUNAD,MARKA,KATEGORIAD,URUNSTOK,URUNSATISFIYAT,URUNALISFIYAT,(URUNSATISFIYAT-URUNALISFIYAT) AS 'KAR',(URUNSATISFIYAT-URUNALISFIYAT)*URUNSTOK AS 'TOPLAM KAR' FROM TBLURUNLER
INNER JOIN TBLKATEGORI
ON TBLURUNLER.URUNKATEGORI=TBLKATEGORI.KATEGORIID

--TOPLAM KAR 1000 TLNÝN ALTINDA KALAN ÜRÜNLERÝN STIÞ FÝYATINA %20ZAM YAP
UPDATE TBLURUNLER SET URUNSATISFIYAT=URUNSATISFIYAT*1.2 
WHERE (URUNSATISFIYAT-URUNALISFIYAT)*URUNSTOK < 1000