--LEFT JOIN

SELECT * FROM TBLNOTLAR
INNER JOIN TBLOGRENCILER
ON TBLNOTLAR.OGRENCI=TBLOGRENCILER.OGRID


SELECT * FROM TBLNOTLAR
LEFT JOIN TBLOGRENCILER
ON TBLNOTLAR.OGRENCI=TBLOGRENCILER.OGRID


SELECT * FROM TBLNOTLAR
RIGHT JOIN TBLOGRENCILER
ON TBLNOTLAR.OGRENCI=TBLOGRENCILER.OGRID
