
--BÝRLEÞTÝRMELER


SELECT OGRAD+' '+OGRSOYAD AS [OGRENCI],DERSAD,SINAV1,SINAV2,SINAV3,ORTALAMA,DURUM FROM TBLNOTLAR
JOIN TBL_DERSLER 
ON TBLNOTLAR.DERS=TBL_DERSLER.DERSID
JOIN TBLOGRENCILER
ON TBLNOTLAR.OGRENCI=TBLOGRENCILER.OGRID


--ALT SORGULAR

/*DERSLER TABLOSUNDA ÝSMÝ MATEMATÝK OLAN DERSE AÝT SINAV NOTLARINI GÖRÜNTÜLEMEK ÝSTÝYORUZ*/

SELECT * FROM TBLNOTLAR
WHERE DERS=(SELECT DERSID FROM TBL_DERSLER WHERE DERSAD='MATEMATÝK')

/*DERSLER TABLOSUNDA ALGORÝTMA DERSÝNE AÝT EN YÜKSEK SINAV 1 NOTUNU GETÝR */
SELECT MAX(SINAV1) AS [1. SINAV EN YÜKSEK NOTU] FROM TBLNOTLAR
WHERE DERS=(SELECT DERSID FROM TBL_DERSLER WHERE DERSAD='TÜRKÇE')


