
--SELECT

SELECT * FROM TBLOGRENCILER

SELECT OGRSEHIR FROM TBLOGRENCILER

SELECT OGRAD,OGRSOYAD FROM TBLOGRENCILER

--INSERT INTO

INSERT INTO TBLOGRENCILER (OGRAD,OGRSOYAD,OGRSEHIR) VALUES ('ÞULE','MEÞE','BURSA')
SELECT * FROM TBLOGRENCILER


--DELETE FROM
DELETE FROM TBLOGRENCILER WHERE OGRID=6

--TRUNCATE
TRUNCATE TABLE TBLOGRENCILER

--UPDATE
UPDATE TBLOGRENCILER SET OGRCINSIYET='ERKEK' 

UPDATE TBLOGRENCILER SET OGRCINSIYET='ERKEK' WHERE OGRID=1

UPDATE TBLOGRENCILER SET OGRKULUP='KÝTAPLIK' WHERE OGRAD='ALÝ'

--AGGREGATE FUNCTIONS

select * from TBLOGRENCILER

select count(OGRID) from TBLOGRENCILER

select sum(OGRID) FROM TBLOGRENCILER

SELECT COUNT(*) AS [TOPLAM KÝÞÝ SAYISI] FROM TBLOGRENCILER

SELECT COUNT(*) AS [TOPLAM KÝÞÝ SAYISI] FROM TBLOGRENCILER WHERE OGRSEHIR = 'Adana'

SELECT AVG(SINAV1) AS [1. SINAV ORTALAMASI], AVG(SINAV2) AS [2. SINAV ORTALAMASI] FROM TBLNOTLAR

SELECT MAX(SINAV1) AS [1. SINAVIN EN YÜKSEK NOTU],MAX(SINAV2) AS [2. SINAVIN EN YÜKSEK NOTU] FROM TBLNOTLAR


--GROUP BY 

SELECT OGRSEHIR,COUNT(*) AS [ÞEHÝRDEKÝ ÖÐRENCÝ SAYISI]  FROM TBLOGRENCILER
GROUP BY OGRSEHIR

SELECT OGRCINSIYET, COUNT(*) AS [KÝÞÝ SAYISI] FROM TBLOGRENCILER
GROUP BY OGRCINSIYET

SELECT DURUM,COUNT(*) AS [TOPLAM ÖÐRENCÝ SAYISI]  FROM TBLNOTLAR
GROUP BY DURUM

SELECT OGRKULUP,COUNT(*) FROM TBLOGRENCILER
GROUP BY OGRKULUP


--HAVING

SELECT OGRSEHIR,COUNT(*) AS [TOPLAM KÝÞÝ SAYISI] FROM TBLOGRENCILER
GROUP BY OGRSEHIR
HAVING COUNT(*)=2

SELECT OGRKULUP,COUNT(*) AS [TOPLAM] FROM TBLOGRENCILER
GROUP BY OGRKULUP
HAVING COUNT(*)<5

SELECT DURUM,COUNT(*) AS [TOPLAM] FROM TBLNOTLAR
GROUP BY DURUM
HAVING DURUM=1


--LIKE OPERATÖRÜ
select * from TBLOGRENCILER
where OGRAD LIKE 'A%'

SELECT * FROM TBLOGRENCILER
WHERE OGRSEHIR NOT LIKE '%AR%'

--DISTINCT ANAHTAR KELÝMESÝ

SELECT DISTINCT OGRAD FROM TBLOGRENCILER

SELECT COUNT(DISTINCT OGRSEHIR) FROM TBLOGRENCILER

--ORDER BY

SELECT * FROM TBLOGRENCILER
ORDER BY OGRKULUP

SELECT * FROM TBLOGRENCILER
ORDER BY OGRSEHIR

SELECT * FROM TBLNOTLAR
ORDER BY ORTALAMA

--SELECT TOP

SELECT TOP 3 * FROM TBLOGRENCILER

SELECT TOP 3 PERCENT * FROM TBLOGRENCILER


--IN OPERATÖRÜ

SELECT * FROM TBLOGRENCILER
WHERE OGRSEHIR IN ('ANKARA','ELAZIÐ')


--BETWEEN OPERATÖRÜ

SELECT * FROM TBLNOTLAR
WHERE ORTALAMA BETWEEN 50 AND 60