--PROSEDÜRLER

--prosedür uzun sql sorgularýný birkere yazýp istediðimiz yerde 
--tekrar tekrar çaðýrmamýzý saðlayan fonksiyonlar gibidir

--PROCEDURE OLUÞTURMA
CREATE PROCEDURE HAREKETLER 
AS
SELECT  HAREKETID, URUNAD AS ÜRÜN,MUSTERIAD + ' '+ MUSTERISOYAD AS [MÜÞTERÝ],PERSONELAD AS PERSONEL,ADET,TUTAR,TARIH AS [SATIÞ TARÝHÝ] FROM TBLHAREKET
INNER JOIN TBLURUNLER
ON TBLHAREKET.URUN = TBLURUNLER.URUNID
INNER JOIN TBLMUSTERI
ON TBLHAREKET.MUSTERI = TBLMUSTERI.MUSTERIID
INNER JOIN TBLPERSONEL
ON TBLHAREKET.PERSONEL = TBLPERSONEL.PERSONELID


--PROCEDURE ÇALIÞTIRMA
EXECUTE HAREKETLER

--EXECUTE ÝLE AYNIDIR
EXEC HAREKETLER


--PROSEDÜRÜ SÝLER
DROP PROCEDURE HAREKETLER

--PROSEDÜRÜ GÜNCELLEME
ALTER PROCEDURE [dbo].[HAREKETLER]
AS
SELECT  HAREKETID, URUNAD AS ÜRÜN,MUSTERIAD + ' '+ MUSTERISOYAD AS [MÜÞTERÝ],SUBSTRING(PERSONELAD,1,1) AS PERSONEL,ADET,TUTAR,TARIH AS [SATIÞ TARÝHÝ] FROM TBLHAREKET
INNER JOIN TBLURUNLER
ON TBLHAREKET.URUN = TBLURUNLER.URUNID
INNER JOIN TBLMUSTERI
ON TBLHAREKET.MUSTERI = TBLMUSTERI.MUSTERIID
INNER JOIN TBLPERSONEL
ON TBLHAREKET.PERSONEL = TBLPERSONEL.PERSONELID



--PARAMETRELÝ  PROSEDÜR OLUÞTURMA
CREATE PROCEDURE URUNLÝSTESÝGETÝR
@DEGER VARCHAR(50) = 'BUZDOLABI'  --DEÐÝÞKEN TANIMLADIK
AS
SELECT * FROM TBLURUNLER
WHERE URUNAD=@DEGER

--DEFAULT VALUE ÝLE PROSEDÜRÜ ÇALIÞTIRIR
EXEC URUNLÝSTESÝGETÝR

--DEÐER DEÐÝÞKENÝNE YENÝ DEÐER ATAYARAK PROSEDÜRÜ ÇALIÞTIRIR. 
EXEC URUNLÝSTESÝGETÝR @DEGER = 'LAPTOP'