/* STRÝNG FONKSÝYONLAR */


--UPPER() BÜYÜK HARFE ÇEVÝRÝR
select upper('sule mese') as [BÜYÜK HARF]



--LOWER() KÜÇÜK HARFE ÇEVÝRÝR
select lower('SULE MESE') as [KÜÇÜK HARF]



--LEN() UZUNLUK DÖNDÜRÜR
select len('sule mese') as UZUNLUK



--LTRIM() - BAÞTAKÝ BOÞLUKLARI TEMÝZLER
select ltrim('          sulemese') as TEMÝZLENMÝÞ



--RTRIM() - SONDAKÝ BOÞLUKLARI TEMÝZLER
select rtrim('sulemese     ') as temizlenmiþ



--SUBSTRING() -METNÝN BÝR BÖLÜMÜNÜ ALIR
select SUBSTRING('sulemese',1,4) as [ALT PARÇA] 




--REPLACE() - METNÝN ÝÇÝNDEKÝ KARAKTERÝ DEÐÝÞTÝRÝR
select REPLACE('sulemese','e','a') as degisen



--CONCAT() METÝNLERÝ BÝRLEÞTÝRÝR
select CONCAT('sule','mese') as birlestirilmiþ 



--CHARINDEX() - METÝNDE ARANAN DEÐERÝN KAÇINCI KARAKTER OLDUÐUNU VERÝR
select CHARINDEX('a' ,'sql derslerine devam')
--aramaya 6. karakterden baþlasýn dersek parametre veririz. 
select CHARINDEX('s','sql derslerine devam',6) 




--REVERSE() - METNÝ TERSTEN YAZAR
select REVERSE('ali')



--TABLOLARLA ÖRNEKLER
SELECT SUBSTRING(OGRAD,1,3) AS [PARÇALAR] FROM TBLOGRENCILER

SELECT LOWER(OGRAD) AS [KÜÇÜKHARF] FROM TBLOGRENCILER

SELECT CONCAT(OGRCINSIYET,'-',OGRAD) FROM TBLOGRENCILER

SELECT REPLACE(OGRAD,'e','a') FROM TBLOGRENCILER

SELECT OGRAD, SUBSTRING(KULUPAD,1,3) AS SONUC FROM TBLOGRENCILER
INNER JOIN TBLKULUPLER
ON TBLOGRENCILER.OGRKULUP = TBLKULUPLER.KULUPID


SELECT OGRAD,LEN(OGRAD),OGRKULUP FROM TBLOGRENCILER
WHERE OGRSEHIR='ÝZMÝR' AND OGRKULUP=(SELECT KULUPID FROM TBLKULUPLER WHERE KULUPAD='KÝTAPLIK' )

SELECT OGRAD FROM TBLOGRENCILER
WHERE LEN(OGRAD) BETWEEN 3 AND 4


SELECT CHARINDEX('A',OGRAD,1) FROM TBLOGRENCILER

