--ürünler içinden her bir ürün kaç adet satýlmýþ bunu getirelim
select URUNAD,count(*) AS 'Satýþ Sayýsý'from TBLHAREKET
JOIN TBLURUNLER
ON TBLHAREKET.URUN=TBLURUNLER.URUNID
group by URUNAD
Order by count(*)


--ürünler tablosunda sadece kategorisi bilgisayar olan ürünlerin satýþ sayýsýný getir
select * from TBLHAREKET
where URUN IN(select URUNID from TBLURUNLER where URUNKATEGORI=(select KATEGORIID from TBLKATEGORI where KATEGORIAD='Beyaz Eþya'))


--HAREKET SORGUSU TABLOSU ÝÇÝNDE ÞEHRÝ ADANA OLAN MÜÞTERÝLERÝN HARCAMALARINI BULALIM
select TUTAR from TBLHAREKET
where MUSTERI IN(SELECT MUSTERIID FROM TBLMUSTERI WHERE MUSTERISEHIR='ADANA')

--BEYAZ EÞYA KATEGORÝSÝNDE YAPILAN HARCAMALARI LÝSTELEYEN SORGU
SELECT TUTAR FROM TBLHAREKET
WHERE URUN IN (SELECT URUNID FROM TBLURUNLER WHERE URUNKATEGORI=(SELECT KATEGORIID FROM TBLKATEGORI WHERE KATEGORIAD='BEYAZ EÞYA'))

--ADANALI VEYA ANKARALI MÜÞTERÝLERE SATILAN ÜRÜNLERÝN TOPLAM FÝYATI
SELECT SUM(TUTAR) FROM TBLHAREKET
WHERE MUSTERI IN(SELECT MUSTERIID FROM TBLMUSTERI WHERE MUSTERISEHIR IN('ADANA','ANKARA','BURSA')


